export const poolAbi =
    [
        { "inputs": [{ "internalType": "uint8", "name": "id", "type": "uint8" }], "name": "getEModeCategoryData", "outputs": [{ "components": [{ "internalType": "uint16", "name": "ltv", "type": "uint16" }, { "internalType": "uint16", "name": "liquidationThreshold", "type": "uint16" }, { "internalType": "uint16", "name": "liquidationBonus", "type": "uint16" }, { "internalType": "address", "name": "priceSource", "type": "address" }, { "internalType": "string", "name": "label", "type": "string" }], "internalType": "struct DataTypes.EModeCategoryLegacy", "name": "", "type": "tuple" }], "stateMutability": "view", "type": "function" },
        { "inputs": [{ "internalType": "uint8", "name": "id", "type": "uint8" }], "name": "getEModeCategoryCollateralBitmap", "outputs": [{ "internalType": "uint128", "name": "", "type": "uint128" }], "stateMutability": "view", "type": "function" },
        { "inputs": [{ "internalType": "address", "name": "user", "type": "address" }], "name": "getUserEMode", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" },
        { "inputs": [{ "internalType": "address", "name": "user", "type": "address" }], "name": "getUserAccountData", "outputs": [{ "internalType": "uint256", "name": "totalCollateralBase", "type": "uint256" }, { "internalType": "uint256", "name": "totalDebtBase", "type": "uint256" }, { "internalType": "uint256", "name": "availableBorrowsBase", "type": "uint256" }, { "internalType": "uint256", "name": "currentLiquidationThreshold", "type": "uint256" }, { "internalType": "uint256", "name": "ltv", "type": "uint256" }, { "internalType": "uint256", "name": "healthFactor", "type": "uint256" }], "stateMutability": "view", "type": "function" },
        { "inputs": [], "name": "getReservesList", "outputs": [{ "internalType": "address[]", "name": "", "type": "address[]" }], "stateMutability": "view", "type": "function" },
        //EVENTS
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "collateralAsset", "type": "address" }, { "indexed": true, "internalType": "address", "name": "debtAsset", "type": "address" }, { "indexed": true, "internalType": "address", "name": "user", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "debtToCover", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "liquidatedCollateralAmount", "type": "uint256" }, { "indexed": false, "internalType": "address", "name": "liquidator", "type": "address" }, { "indexed": false, "internalType": "bool", "name": "receiveAToken", "type": "bool" }], "name": "LiquidationCall", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "reserve", "type": "address" }, { "indexed": false, "internalType": "address", "name": "user", "type": "address" }, { "indexed": true, "internalType": "address", "name": "onBehalfOf", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "amount", "type": "uint256" }, { "indexed": false, "internalType": "enum DataTypes.InterestRateMode", "name": "interestRateMode", "type": "uint8" }, { "indexed": false, "internalType": "uint256", "name": "borrowRate", "type": "uint256" }, { "indexed": true, "internalType": "uint16", "name": "referralCode", "type": "uint16" }], "name": "Borrow", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "reserve", "type": "address" }, { "indexed": false, "internalType": "address", "name": "caller", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "amountCovered", "type": "uint256" }], "name": "DeficitCovered", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "user", "type": "address" }, { "indexed": true, "internalType": "address", "name": "debtAsset", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "amountCreated", "type": "uint256" }], "name": "DeficitCreated", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "asset", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "totalDebt", "type": "uint256" }], "name": "IsolationModeTotalDebtUpdated", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "reserve", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "amountMinted", "type": "uint256" }], "name": "MintedToTreasury", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "user", "type": "address" }, { "indexed": true, "internalType": "address", "name": "positionManager", "type": "address" }], "name": "PositionManagerApproved", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "user", "type": "address" }, { "indexed": true, "internalType": "address", "name": "positionManager", "type": "address" }], "name": "PositionManagerRevoked", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "reserve", "type": "address" }, { "indexed": true, "internalType": "address", "name": "user", "type": "address" }, { "indexed": true, "internalType": "address", "name": "repayer", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "amount", "type": "uint256" }, { "indexed": false, "internalType": "bool", "name": "useATokens", "type": "bool" }], "name": "Repay", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "reserve", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "liquidityRate", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "stableBorrowRate", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "variableBorrowRate", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "liquidityIndex", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "variableBorrowIndex", "type": "uint256" }], "name": "ReserveDataUpdated", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "reserve", "type": "address" }, { "indexed": true, "internalType": "address", "name": "user", "type": "address" }], "name": "ReserveUsedAsCollateralDisabled", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "reserve", "type": "address" }, { "indexed": true, "internalType": "address", "name": "user", "type": "address" }], "name": "ReserveUsedAsCollateralEnabled", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "reserve", "type": "address" }, { "indexed": false, "internalType": "address", "name": "user", "type": "address" }, { "indexed": true, "internalType": "address", "name": "onBehalfOf", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "amount", "type": "uint256" }, { "indexed": true, "internalType": "uint16", "name": "referralCode", "type": "uint16" }], "name": "Supply", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "user", "type": "address" }, { "indexed": false, "internalType": "uint8", "name": "categoryId", "type": "uint8" }], "name": "UserEModeSet", "type": "event" },
        { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "reserve", "type": "address" }, { "indexed": true, "internalType": "address", "name": "user", "type": "address" }, { "indexed": true, "internalType": "address", "name": "to", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "amount", "type": "uint256" }], "name": "Withdraw", "type": "event" }
    ];